export enum SolutionChoice {
  NONE = 'NONE',
  SHARED_DATABASE = 'SHARED_DATABASE',
  STAFF_EDUCATION = 'STAFF_EDUCATION',
  VTM_VERIFICATION_REMOVAL = 'VTM_VERIFICATION_REMOVAL',
  ERROR_PREVENTION = 'ERROR_PREVENTION'
}
