export enum State {
  ARRIVE = 'ARRIVE',
  MAIN_QUEUE = 'MAIN_QUEUE',
  QUEUE_MANAGER_DISCUSSION = 'QUEUE_MANAGER_DISCUSSION',
  APP_BOOTHS = 'APP_BOOTHS',
  COUNTERS = 'COUNTERS',
  ATMS = 'ATMS',
  ATM_COINS = 'ATM_COINS',
  VTMS = 'VTMS',
  RETURNING_LATER_QN = 'RETURNING_LATER_QN',
  RETURNING_LATER_QA = 'RETURNING_LATER_QA',
  EXIT = 'EXIT'
}
